### ISSUE TITLE
index.js can't find variable: DRAWER_WIDTH error

### ISSUE THREAD

**Issue by muratboyraz** [pedreviljoen/react-native-menu#23]
Hi, 
I was just trying this example https://reactnativeexample.com/simple-lightweight-customisable-menu-drawer-component/ and there was an error in index.js file which you may forgot to declare DRAWER_WIDTH value.

**Comment by pedreviljoen** [comment]
@muratboyraz Will have a look 👍

**Comment by pedreviljoen** [comment]
Did you pass the drawer percentage through as a prop?

**Comment by muratboyraz** [comment]
> Did you pass the drawer percentage through as a prop? It is a percentage value between 0 and 100.

yes i did, but i got same error. I inspected your code and i add DRAWER_WIDTH as a global variable, after that time it compiled but result looks like this. 
![drawer_width](https://user-images.githubusercontent.com/32867999/56379928-8c5b2a00-6219-11e9-8f3c-ffb374e1c3b6.PNG)
- I am beginner in react-native by the way. May be i am doing something wrong. -

**Comment by pedreviljoen** [comment]
Updated to accommodate. You can upgrade your dependency to match latest version & re-install 👍🏼

**Comment by pedreviljoen** [comment]
@muratboyraz updated with a fix. Please update to latest package dependency and try again :)
