### ISSUE TITLE
I cant click open. It is not working

### ISSUE THREAD

**Issue by RAGU7063** [pedreviljoen/react-native-menu#34]
I cant click open label. It is not working. Please check yourself and confirm

**Comment by pedreviljoen** [comment]
@RAGU7063 
Thanks for reporting this issue. However, the demo of the component as you see it in the Readme, is where the component was used within a mock project. Open will not appear when you install and import the component.

<img width="886" alt="Screenshot 2019-05-14 at 09 05 06" src="https://user-images.githubusercontent.com/22566407/57677556-66158800-7627-11e9-9d2f-b2befdbdf356.png">

As seen in the snippet, there is a boolean property that toggles the menu drawer to be open or closed.

Let me know if this answers your question or resolves your issue.
