### ISSUE TITLE
Drawer menu won't come up on Android 

### ISSUE THREAD

**Issue by LeoUrushi** [pedreviljoen/react-native-menu#35]
The drawer menu works nicely on iOS. 
When I switch to Android environment, the side drawer will no longer show up. 

**To Reproduce**
1. Open the build on Android simulator 
2. Click the button to reveal the side menu 
3. The menu will not come up 

**Expected behavior**
Side menu will become visible 

**Desktop (please complete the following information):**
 - OS: macOS Mojave (version 10.14) 
 - XCode: Version version 10.1 
 - React 16.6.3 
 - React Native 0.58.4

**Comment by pedreviljoen** [comment]
Thanks will look into it and revert back 😊

**Comment by Neha1405** [comment]
same issue , In Android it's not working even it looks like the phone is hanging.

**Comment by pedreviljoen** [comment]
@Neha1405 @LeoUrushi 
Will look into and report fix (or update) on this thread, thanks 👍

**Comment by pedreviljoen** [comment]
Fixed, please install package again to v1.1.6 to resolve this issue :)

**Comment by Neha1405** [comment]
Thanks a lot :)
