### ISSUE TITLE
It would be nice have to animation right to left

### ISSUE THREAD

**Issue by istudiohtml** [pedreviljoen/react-native-menu#38]
Hey, It is very good help me a lot for my projects. It would be nice if  it have setting for animation right to left (now only left to right )
Thank you.

**Comment by pedreviljoen** [comment]
@istudiohtml 
Hey, thanks. Will let you know when implemented 😄

**Comment by pedreviljoen** [comment]
@istudiohtml 
Closing this issue, as it is a feature request 😄
