### ISSUE TITLE
Zindex for ios device

### ISSUE THREAD

**Issue by mayankpandav** [pedreviljoen/react-native-menu#48]
@pedreviljoen  im facing some issue with drawer on iphone 
You can see our testing code here....
https://snack.expo.io/@immynk/shipmug
while navigating menu its hide inside other views.... and aslo they put horizontal line on status bar
![image](https://user-images.githubusercontent.com/23099407/61973475-b898fa80-b001-11e9-94c2-b564ea6221c1.png)
status bar
![image](https://user-images.githubusercontent.com/23099407/61973541-dbc3aa00-b001-11e9-95bb-8e6542ef04ff.png)

**Comment by pedreviljoen** [comment]
@mayankpandav Cool thanks, will have a look 👍

**Comment by pedreviljoen** [comment]
@mayankpandav 
Can't seem to find where you've used it in your Expo snack

**Comment by mayankpandav** [comment]
you can see on component -> topbar -> index file
