### ISSUE TITLE
Rotating to landscape

### ISSUE THREAD

**Issue by lgspacil** [pedreviljoen/react-native-menu#50]
I have an issue when I rotate my screen to landscape, the content isn't allowed to extend the full width of the screen. When I remove the MenuDrawer component, the app becomes responsive once again. 

Any ideas on how to fix this?

**Comment by pedreviljoen** [comment]
@lgspacil 
I will need to accommodate for landscape functionality. At the moment the dimensions of the screen width and height are not re-calculated on viewport change. Thanks for the heads up 👍

**Comment by alexanderkho** [comment]
@pedreviljoen any update on this feature? I'd like to use this component for it's simplicity but I am running into this issue as well.
