### ISSUE TITLE
Opacity bug on closing

### ISSUE THREAD

**Issue by jcdiprose** [pedreviljoen/react-native-menu#72]
**Describe the bug**
When closing the side menu, it flickers in opacity making it translucent for a moment at the beginning of the animation closing.

**To Reproduce**
1. Set the menu to 3000 or 5000 animationTime
2. set a bright background and dark menu background
3. Open menu then close menu to see it happen

**Expected behavior**
The menu should fade gracefully

**Screenshots**
**1**
[https://ibb.co/0V0X6wQ](url)
**2**
[https://ibb.co/5LbnYzg](url)

**Desktop (please complete the following information):**
Android emulator

**Comment by jcdiprose** [comment]
I've been looking at your code and can't see where this issue is coming from. Though i'm going to continue looking

**Comment by pedreviljoen** [comment]
@jcdiprose 
Do you mind providing the Android emulator used please?
