### ISSUE TITLE
Switching from portrait to landscape size issue

### ISSUE THREAD

**Issue by sdattatri** [pedreviljoen/react-native-menu#77]
**Describe the bug**
I have settings as follows: 
```
<MenuDrawer
        open={menuOpenRef.current}
        drawerContent={menuContent()}
        drawerPercentage={100}
        animationTime={200}
        overlay={true}
        opacity={0.4}
 >
```
When I flip the phone from portrait to landscape, the dimensions of the menu remain the same. So now in landscape only part of the screen behind is covered by the menu. It appears that the height and width of the top window of the MenuDrawer component remain fixed even when the orientation is changed.
**To Reproduce**
Just flip the phone from portrait to landscape.
**Expected behavior**
Size recalculated and redrawn

**Screenshots**
![WhatsApp Image 2020-11-11 at 2 37 02 PM](https://user-images.githubusercontent.com/26168621/98791971-d0c99e80-242b-11eb-8b3b-3bb2744a0f71.jpeg)
![WhatsApp Image 2020-11-11 at 2 36 53 PM](https://user-images.githubusercontent.com/26168621/98792048-e9d24f80-242b-11eb-9b77-698d9bd3df3a.jpeg)

**Comment by pedreviljoen** [comment]
@sdattatri 
At this moment landscape is not supported.

**Comment by damau** [comment]
Heya @sdattatri and @pedreviljoen this should make it portrait compatible.  @sdattatri Love it if you could give it a try.

(I don't class myself as a react-native dev, so performance may be an issue)
https://github.com/pedreviljoen/react-native-menu/pull/90
