### ISSUE TITLE
Android has a space at the bottom of the screen.

### ISSUE THREAD

**Issue by patrickdunagan** [pedreviljoen/react-native-menu#80]
**Describe the bug**
In android, it appears there is a small gap (~35px) in height.  It does not show up in IOS.  

**To Reproduce**
1. Create a drawer and run on android.

**Expected behavior**
No Gap

**Smartphone (please complete the following information):**
 - Device: [Motorola Motog plus]
 - OS: [android 9]
 - Version [1.2.9]

**Additional context**
I added 37 to SCREEN_HEIGHT when Platform.OS == "android" in index.  Solved my issue for now.

This solves my problem.  I have not tested on any other android devices, I could not tell you if this is device issue or android issue.

Thank you,

Patrick

**Comment by AndreLaranjeira** [comment]
@patrickdunagan I have experienced the same issue recently. Were you by any chance using expo header on your application?

**Comment by pedreviljoen** [comment]
Thanks @patrickdunagan 

Will take a look into this
