### ISSUE TITLE
Main content is not clickable or scrollable when overlay = false (even when drawer is hidden)

### ISSUE THREAD

**Issue by mazensharkawy** [pedreviljoen/react-native-menu#81]
Main content is not clickable or scrollable when overlay = false (even when drawer is hidden)
You can see main content but can't interact with it.
However as soon as i change it to overlay = true .. everything works

Tested on android 8.1 and android 11

**Comment by pedreviljoen** [comment]
@mazensharkawy 
Please check out the bug report to raise awareness for a bug: https://github.com/pedreviljoen/react-native-menu/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
